// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

console.log("Hello, BuckleScript and Reason!");

function addToCart(c, i) {
  if (typeof c === "number") {
    return /* ActiveCart */Block.__(0, [/* :: */[
                i,
                /* [] */0
              ]]);
  } else if (c.tag) {
    return c;
  } else {
    return /* ActiveCart */Block.__(0, [/* :: */[
                i,
                c[0]
              ]]);
  }
}

var c = /* ActiveCart */Block.__(0, [/* :: */[
      "iPhone XR",
      /* [] */0
    ]]);

console.log(c);

var ageAndName = /* tuple */[
  33,
  "Gabriel"
];

var me = /* record */[
  /* age */5,
  /* name */"Big Reason"
];

exports.ageAndName = ageAndName;
exports.me = me;
exports.addToCart = addToCart;
exports.c = c;
/*  Not a pure module */
